import React, { useState, useEffect, useCallback } from 'react';
import {
  Users,
  Target,
  BarChart3,
  CheckCircle,
  Download,
  FileSpreadsheet,
  ChevronDown,
  TrendingUp,
  MessageCircle,
  Star,
  ChevronRight,
  Clock,
  AlertCircle,
  RefreshCw,
  Calendar,
  BarChart2,
} from 'lucide-react';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
  LabelList,
} from 'recharts';
import { Button } from '../components/common/Button';
import { StatCard } from '../components/common/StatCard';
import { StatCardSkeleton, ChartSkeleton } from '../components/common/Skeleton';
import { EmptyState } from '../components/common/EmptyState';
import { ErrorState } from '../components/common/ErrorState';
import { reportService } from '../services/reportService';
import type {
  ReportStats,
  LeadGrowthDataPoint,
  LeadSourceDataPoint,
  StatusBreakdownDataPoint,
  TopRequirementDataPoint,
  FollowUpPerformanceData,
  ReportHighlight,
} from '../types/report';

export const Reports: React.FC = () => {
  const [stats, setStats] = useState<ReportStats | null>(null);
  const [leadGrowth, setLeadGrowth] = useState<LeadGrowthDataPoint[]>([]);
  const [leadSources, setLeadSources] = useState<LeadSourceDataPoint[]>([]);
  const [statusBreakdown, setStatusBreakdown] = useState<StatusBreakdownDataPoint[]>([]);
  const [topRequirements, setTopRequirements] = useState<TopRequirementDataPoint[]>([]);
  const [performance, setPerformance] = useState<FollowUpPerformanceData | null>(null);
  const [highlights, setHighlights] = useState<ReportHighlight[]>([]);

  const [timeframe, setTimeframe] = useState('This Month');
  const [showTimeframeMenu, setShowTimeframeMenu] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchAllReportData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const [
        statsData,
        growthData,
        sourcesData,
        statusData,
        reqsData,
        perfData,
        highData,
      ] = await Promise.all([
        reportService.getReportStats(timeframe).catch(() => null),
        reportService.getLeadGrowth(timeframe).catch(() => []),
        reportService.getLeadSources(timeframe).catch(() => []),
        reportService.getStatusBreakdown().catch(() => []),
        reportService.getTopRequirements().catch(() => []),
        reportService.getFollowUpPerformance().catch(() => null),
        reportService.getReportHighlights().catch(() => []),
      ]);

      setStats(statsData);
      setLeadGrowth(growthData || []);
      setLeadSources(sourcesData || []);
      setStatusBreakdown(statusData || []);
      setTopRequirements(reqsData || []);
      setPerformance(perfData);
      setHighlights(highData || []);
    } catch (err: any) {
      setError(err.message || 'Unable to load report data from server.');
    } finally {
      setLoading(false);
    }
  }, [timeframe]);

  useEffect(() => {
    fetchAllReportData();
  }, [fetchAllReportData]);

  const handleExport = () => {
    const csvContent =
      'data:text/csv;charset=utf-8,' +
      'Metric,Value\n' +
      `Total Leads,${stats?.totalLeads ?? 0}\n` +
      `Interested Leads,${stats?.interestedLeads ?? 0}\n` +
      `Conversion Rate,${stats?.conversionRate ?? 0}%\n` +
      `Follow-up Completion Rate,${stats?.followUpCompletionRate ?? 0}%\n\n` +
      'Top Requirements,Leads\n' +
      topRequirements.map((r) => `"${r.requirement}",${r.leads}`).join('\n');

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `appra_crm_report_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleGenerateReport = () => {
    alert('Report generation triggered. Real PDF export will download once generated by backend.');
  };

  // Color palette for charts
  const defaultColors = ['#2563eb', '#10b981', '#8b5cf6', '#f59e0b', '#ec4899', '#94a3b8'];

  // Total count for donut
  const totalDonutLeads = leadSources.reduce((acc, curr) => acc + curr.value, 0);

  return (
    <div className="p-4 sm:p-6 lg:p-7 max-w-[1400px] mx-auto space-y-6">
      {/* Top Header */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight">
            Reports
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
            Track lead performance, follow-up efficiency, and customer conversions.
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-2.5">
          {/* Timeframe selector dropdown */}
          <div className="relative">
            <button
              onClick={() => setShowTimeframeMenu(!showTimeframeMenu)}
              className="flex items-center gap-2 text-xs font-medium text-slate-700 bg-white border border-slate-200 px-3.5 py-2 rounded-lg shadow-2xs hover:bg-slate-50 transition-colors cursor-pointer"
            >
              <Calendar className="w-3.5 h-3.5 text-slate-500" />
              <span>{timeframe}</span>
              <ChevronDown className="w-3.5 h-3.5 text-slate-400 ml-1" />
            </button>

            {showTimeframeMenu && (
              <div className="absolute top-full mt-1.5 right-0 bg-white border border-slate-200 rounded-lg shadow-lg py-1 z-30 w-36 animate-in fade-in duration-100">
                {['This Month', 'Last Month', 'This Quarter', 'This Year'].map((tf) => (
                  <button
                    key={tf}
                    onClick={() => {
                      setTimeframe(tf);
                      setShowTimeframeMenu(false);
                    }}
                    className={`w-full text-left px-3 py-1.5 text-xs cursor-pointer ${
                      timeframe === tf ? 'bg-blue-50 text-blue-600 font-semibold' : 'text-slate-700 hover:bg-slate-50'
                    }`}
                  >
                    {tf}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Export Report Button */}
          <Button
            variant="outline"
            size="md"
            icon={<Download className="w-4 h-4 text-slate-600" />}
            onClick={handleExport}
            className="text-xs font-semibold"
          >
            Export Report
          </Button>

          {/* Generate Report Button */}
          <Button
            variant="primary"
            size="md"
            icon={<FileSpreadsheet className="w-4 h-4" />}
            onClick={handleGenerateReport}
            className="text-xs font-semibold"
          >
            Generate Report
          </Button>
        </div>
      </div>

      {/* Error state if server error */}
      {error && !loading && (
        <ErrorState
          title="Reports unavailable"
          message={error}
          onRetry={fetchAllReportData}
          className="bg-white border border-slate-200 rounded-xl p-8 shadow-xs"
        />
      )}

      {/* 4 KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {loading ? (
          <>
            <StatCardSkeleton />
            <StatCardSkeleton />
            <StatCardSkeleton />
            <StatCardSkeleton />
          </>
        ) : (
          <>
            {/* Total Leads */}
            <StatCard
              title="Total Leads"
              value={stats?.totalLeads ?? 0}
              icon={<Users className="w-5 h-5" />}
              variant="blue"
              growthText={
                stats?.totalLeadsGrowth !== undefined
                  ? `↑ ${stats.totalLeadsGrowth}% from last month`
                  : undefined
              }
              growthType="positive"
            />

            {/* Interested Leads */}
            <StatCard
              title="Interested Leads"
              value={stats?.interestedLeads ?? 0}
              icon={<Target className="w-5 h-5" />}
              variant="green"
              growthText={
                stats?.interestedLeadsGrowth !== undefined
                  ? `↑ ${stats.interestedLeadsGrowth}% from last month`
                  : undefined
              }
              growthType="positive"
            />

            {/* Conversion Rate */}
            <StatCard
              title="Conversion Rate"
              value={`${stats?.conversionRate ?? 0}%`}
              icon={<BarChart3 className="w-5 h-5" />}
              variant="orange"
              growthText={
                stats?.conversionRateGrowth !== undefined
                  ? `↑ ${stats.conversionRateGrowth}% from last month`
                  : undefined
              }
              growthType="positive"
            />

            {/* Follow-up Completion Rate */}
            <StatCard
              title="Follow-up Completion Rate"
              value={`${stats?.followUpCompletionRate ?? 0}%`}
              icon={<CheckCircle className="w-5 h-5" />}
              variant="purple"
              growthText={
                stats?.followUpCompletionRateGrowth !== undefined
                  ? `↑ ${stats.followUpCompletionRateGrowth}% from last month`
                  : undefined
              }
              growthType="positive"
            />
          </>
        )}
      </div>

      {/* ROW 1: Lead Growth & Lead Sources (2 Columns) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Lead Growth (Line & Area Chart) */}
        <div className="lg:col-span-6 bg-white border border-slate-200/80 rounded-xl shadow-xs p-5 flex flex-col justify-between">
          <div className="flex items-center justify-between pb-3">
            <div>
              <h2 className="text-sm font-bold text-slate-900">Lead Growth</h2>
              <p className="text-[11px] text-slate-500 mt-0.5">
                Total leads received over the weeks of this month.
              </p>
            </div>
            <span className="text-[11px] font-medium text-slate-600 bg-slate-50 border border-slate-200 px-2.5 py-1 rounded-md">
              {timeframe}
            </span>
          </div>

          {loading ? (
            <ChartSkeleton height="h-64" />
          ) : leadGrowth.length === 0 ? (
            <div className="h-64 flex items-center justify-center">
              <EmptyState
                icon={<BarChart2 className="w-6 h-6" />}
                title="No lead growth records"
                description="Lead growth trend data will populate here when recorded."
              />
            </div>
          ) : (
            <div className="h-64 w-full pt-2">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart
                  data={leadGrowth}
                  margin={{ top: 20, right: 20, left: -20, bottom: 0 }}
                >
                  <defs>
                    <linearGradient id="leadGrowthGradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.25} />
                      <stop offset="95%" stopColor="#3b82f6" stopOpacity={0.0} />
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis
                    dataKey="week"
                    tickLine={false}
                    axisLine={{ stroke: '#e2e8f0' }}
                    tick={{ fill: '#64748b', fontSize: 11 }}
                  />
                  <YAxis
                    domain={[0, 'auto']}
                    tickLine={false}
                    axisLine={false}
                    tick={{ fill: '#64748b', fontSize: 11 }}
                  />
                  <Tooltip
                    formatter={(val: any) => [`${val} Leads`, 'Leads']}
                    contentStyle={{
                      backgroundColor: '#ffffff',
                      borderRadius: '8px',
                      borderColor: '#e2e8f0',
                      fontSize: '12px',
                      boxShadow: '0 4px 6px -1px rgba(0,0,0,0.08)',
                    }}
                  />
                  <Area
                    type="monotone"
                    dataKey="leads"
                    stroke="#2563eb"
                    strokeWidth={2.5}
                    fillOpacity={1}
                    fill="url(#leadGrowthGradient)"
                    dot={{ r: 4, fill: '#2563eb', stroke: '#ffffff', strokeWidth: 2 }}
                    activeDot={{ r: 6, fill: '#1d4ed8' }}
                  >
                    <LabelList
                      dataKey="leads"
                      position="top"
                      offset={10}
                      style={{ fill: '#0f172a', fontSize: '11px', fontWeight: 600 }}
                    />
                  </Area>
                </AreaChart>
              </ResponsiveContainer>
            </div>
          )}
        </div>

        {/* Right: Lead Sources (Donut Chart) */}
        <div className="lg:col-span-6 bg-white border border-slate-200/80 rounded-xl shadow-xs p-5 flex flex-col justify-between">
          <div className="flex items-center justify-between pb-3">
            <div>
              <h2 className="text-sm font-bold text-slate-900">Lead Sources</h2>
              <p className="text-[11px] text-slate-500 mt-0.5">
                Where your leads are coming from this month.
              </p>
            </div>
            <span className="text-[11px] font-medium text-slate-600 bg-slate-50 border border-slate-200 px-2.5 py-1 rounded-md">
              {timeframe}
            </span>
          </div>

          {loading ? (
            <ChartSkeleton height="h-64" />
          ) : leadSources.length === 0 ? (
            <div className="h-64 flex items-center justify-center">
              <EmptyState
                icon={<BarChart2 className="w-6 h-6" />}
                title="No lead sources found"
                description="Lead channels breakdown will display here once recorded."
              />
            </div>
          ) : (
            <div className="flex flex-col sm:flex-row items-center justify-between gap-6 pt-2">
              {/* Donut Chart with Center Text */}
              <div className="relative w-48 h-48 sm:w-56 sm:h-56 shrink-0 flex items-center justify-center">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={leadSources}
                      cx="50%"
                      cy="50%"
                      innerRadius={55}
                      outerRadius={80}
                      paddingAngle={2}
                      dataKey="value"
                    >
                      {leadSources.map((entry, idx) => (
                        <Cell
                          key={entry.name}
                          fill={entry.color || defaultColors[idx % defaultColors.length]}
                        />
                      ))}
                    </Pie>
                    <Tooltip
                      formatter={(val: any, name: any) => [
                        `${val} leads (${leadSources.find((s) => s.name === name)?.percentage ?? ''}%)`,
                        name,
                      ]}
                    />
                  </PieChart>
                </ResponsiveContainer>

                {/* Centered Donut Label */}
                <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none text-center">
                  <span className="text-xl font-bold text-slate-900 leading-none">
                    {totalDonutLeads}
                  </span>
                  <span className="text-[10px] text-slate-400 font-medium mt-0.5">Total Leads</span>
                </div>
              </div>

              {/* Right Legend */}
              <div className="w-full sm:w-auto flex-1 space-y-2 text-xs">
                {leadSources.map((source, idx) => (
                  <div key={source.name} className="flex items-center justify-between gap-4">
                    <div className="flex items-center gap-2">
                      <span
                        className="w-2.5 h-2.5 rounded-full shrink-0"
                        style={{
                          backgroundColor:
                            source.color || defaultColors[idx % defaultColors.length],
                        }}
                      />
                      <span className="text-slate-700 font-medium">{source.name}</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="font-bold text-slate-900">{source.value}</span>
                      <span className="text-slate-400 text-[11px] w-8 text-right">
                        {source.percentage}%
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ROW 2: Status Breakdown, Top Requirements, Follow-up Performance (3 Columns) */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-12 gap-6">
        {/* Col 1: Status Breakdown (Bar Chart) */}
        <div className="lg:col-span-4 bg-white border border-slate-200/80 rounded-xl shadow-xs p-5 flex flex-col justify-between">
          <div>
            <h2 className="text-sm font-bold text-slate-900">Status Breakdown</h2>
            <p className="text-[11px] text-slate-500 mt-0.5">
              Distribution of leads by current status.
            </p>
          </div>

          {loading ? (
            <ChartSkeleton height="h-56" />
          ) : statusBreakdown.length === 0 ? (
            <div className="h-56 flex items-center justify-center">
              <EmptyState title="No status records" />
            </div>
          ) : (
            <div className="h-56 w-full pt-4">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  data={statusBreakdown}
                  margin={{ top: 20, right: 5, left: -25, bottom: 0 }}
                >
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                  <XAxis
                    dataKey="status"
                    tickLine={false}
                    axisLine={{ stroke: '#e2e8f0' }}
                    tick={{ fill: '#64748b', fontSize: 10 }}
                  />
                  <YAxis
                    domain={[0, 'auto']}
                    tickLine={false}
                    axisLine={false}
                    tick={{ fill: '#64748b', fontSize: 10 }}
                  />
                  <Tooltip
                    formatter={(val: any) => [`${val} Leads`, 'Count']}
                    contentStyle={{
                      backgroundColor: '#ffffff',
                      borderRadius: '8px',
                      borderColor: '#e2e8f0',
                      fontSize: '11px',
                    }}
                  />
                  <Bar dataKey="count" radius={[4, 4, 0, 0]}>
                    {statusBreakdown.map((entry, idx) => (
                      <Cell
                        key={entry.status}
                        fill={entry.color || defaultColors[idx % defaultColors.length]}
                      />
                    ))}
                    <LabelList
                      dataKey="count"
                      position="top"
                      offset={6}
                      style={{ fill: '#0f172a', fontSize: '10px', fontWeight: 600 }}
                    />
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          )}
        </div>

        {/* Col 2: Top Requirements (Table) */}
        <div className="lg:col-span-4 bg-white border border-slate-200/80 rounded-xl shadow-xs p-5 flex flex-col justify-between">
          <div>
            <h2 className="text-sm font-bold text-slate-900">Top Requirements</h2>
            <p className="text-[11px] text-slate-500 mt-0.5">
              Most common customer requirements.
            </p>
          </div>

          {loading ? (
            <div className="space-y-3 py-4">
              {Array.from({ length: 5 }).map((_, i) => (
                <div key={i} className="flex justify-between">
                  <div className="w-32 h-4 bg-slate-100 rounded animate-pulse" />
                  <div className="w-8 h-4 bg-slate-100 rounded animate-pulse" />
                </div>
              ))}
            </div>
          ) : topRequirements.length === 0 ? (
            <div className="py-10 flex items-center justify-center">
              <EmptyState title="No requirement records" />
            </div>
          ) : (
            <div className="mt-3">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="border-b border-slate-100 text-slate-400 font-semibold">
                    <th className="pb-2 font-medium">Requirement</th>
                    <th className="pb-2 font-medium text-right">Leads</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  {topRequirements.map((req) => (
                    <tr key={req.requirement} className="hover:bg-slate-50/60">
                      <td className="py-2.5 font-medium text-slate-700">{req.requirement}</td>
                      <td className="py-2.5 font-bold text-slate-900 text-right">{req.leads}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Col 3: Follow-up Performance */}
        <div className="lg:col-span-4 bg-white border border-slate-200/80 rounded-xl shadow-xs p-5 flex flex-col justify-between">
          <div>
            <h2 className="text-sm font-bold text-slate-900">Follow-up Performance</h2>
            <p className="text-[11px] text-slate-500 mt-0.5">Follow-up activity overview.</p>
          </div>

          {loading ? (
            <div className="space-y-4 py-4">
              {Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="flex justify-between">
                  <div className="w-28 h-4 bg-slate-100 rounded animate-pulse" />
                  <div className="w-8 h-4 bg-slate-100 rounded animate-pulse" />
                </div>
              ))}
            </div>
          ) : !performance ? (
            <div className="py-10 flex items-center justify-center">
              <EmptyState title="No performance data available" />
            </div>
          ) : (
            <div className="space-y-4 my-2">
              <div className="space-y-2.5 text-xs">
                {/* Completed Today */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="w-4 h-4 text-emerald-600" />
                    <span className="text-slate-700 font-medium">Completed Today</span>
                  </div>
                  <span className="font-bold text-slate-900">{performance.completedToday}</span>
                </div>

                {/* Upcoming */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Clock className="w-4 h-4 text-blue-600" />
                    <span className="text-slate-700 font-medium">Upcoming</span>
                  </div>
                  <span className="font-bold text-slate-900">{performance.upcoming}</span>
                </div>

                {/* Overdue */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <AlertCircle className="w-4 h-4 text-rose-600" />
                    <span className="text-slate-700 font-medium">Overdue</span>
                  </div>
                  <span className="font-bold text-slate-900">{performance.overdue}</span>
                </div>

                {/* Rescheduled */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <RefreshCw className="w-4 h-4 text-purple-600" />
                    <span className="text-slate-700 font-medium">Rescheduled</span>
                  </div>
                  <span className="font-bold text-slate-900">{performance.rescheduled}</span>
                </div>
              </div>

              {/* Response Rate Progress Bar */}
              <div className="pt-3 border-t border-slate-100">
                <div className="flex items-center justify-between text-xs mb-1.5">
                  <span className="font-semibold text-slate-700">Response Rate</span>
                  <span className="font-bold text-slate-900">{performance.responseRate}%</span>
                </div>
                <div className="w-full bg-slate-100 rounded-full h-2 overflow-hidden">
                  <div
                    className="bg-emerald-500 h-2 rounded-full transition-all duration-500"
                    style={{ width: `${Math.min(100, performance.responseRate)}%` }}
                  />
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ROW 3: Recent Report Highlights */}
      {!loading && highlights.length > 0 && (
        <div className="space-y-3">
          <div>
            <h2 className="text-sm font-bold text-slate-900">Recent Report Highlights</h2>
            <p className="text-[11px] text-slate-500 mt-0.5">
              Key insights and trends from this month.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {highlights.map((item) => {
              const icons: Record<string, React.ReactNode> = {
                growth: <TrendingUp className="w-4 h-4" />,
                whatsapp: <MessageCircle className="w-4 h-4" />,
                conversion: <Users className="w-4 h-4" />,
                completion: <Star className="w-4 h-4" />,
              };

              return (
                <div
                  key={item.id}
                  className={`p-4 rounded-xl border ${item.borderClass || 'border-slate-200'} ${
                    item.bgClass || 'bg-slate-50'
                  } flex items-center justify-between gap-3 hover:shadow-xs transition-shadow`}
                >
                  <div className="flex items-start gap-3">
                    <div
                      className={`p-2 rounded-lg ${
                        item.iconBgClass || 'bg-blue-100 text-blue-600'
                      } shrink-0 mt-0.5`}
                    >
                      {icons[item.type] || <Star className="w-4 h-4" />}
                    </div>
                    <div>
                      <h3 className="text-xs font-bold text-slate-900 leading-snug">
                        {item.title}
                      </h3>
                      <p
                        className={`text-[11px] font-semibold ${
                          item.textClass || 'text-slate-800'
                        } mt-0.5`}
                      >
                        {item.highlightText}
                      </p>
                      <span className="text-[10px] text-slate-500 mt-0.5 block">
                        {item.subtext}
                      </span>
                    </div>
                  </div>
                  <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};
